name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    #- name: configure
    #  run: ./configure
      
    - name: Install dependencies
      run: sudo apt-get update &&
           sudo apt-get install inkscape potrace npm nodejs fontforge devscripts python3-fontforge python3-pip python3-yaml imagemagick git make debhelper build-essential &&
           sudo npm install -g svgo &&
           sudo pip3 install fonttools 
           #git clone https://github.com/eosrei/twemoji-color-font.git &&
      
    - name: Run make
      run: cd twemoji-color-font &&
           git clone https://github.com/13rac1/scfbuild.git SCFBuild &&
           make -j 4 
           
